.\" SPDX-License-Identifier: GFDL-1.3-or-later
.\" Copyright (C) 2026 South Australia Medical Imaging
.Dd 27 August 2026
.Dt SPIDER_WORKBENCH 1
.Os
.Sh NAME
.Nm spider_workbench
.Nd graphical interface for Spider
.Sh SYNOPSIS
.Nm spider_workbench
.Op ...
.Sh DESCRIPTION
.Nm
is a graphical interface for
.Xr spider 1 .
It supports only a subset of the functionality of
.Xr spider 1 .
.Pp
The options are those accepted by
.Fn Fl::arg
from the version of
.Lk https://www.fltk.org FLTK
against which
.Nm
was built.
.Sh EXIT STATUS
The
.Nm
utility exits with 0 on success, and non-zero if an error occurs.
.Sh SEE ALSO
.Xr spider 1
