name: macos
on:
  # To run the workflow from the Actions tab.
  workflow_dispatch:
jobs:
  build:
    name: Build Spider on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: brew install itk howard-hinnant-date googletest
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_OSX_SYSROOT=macosx
      - name: Build
        run: cmake --build build --verbose
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: cmake --install build
